### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property

### ISSUE THREAD

**Issue by danilofuchs** [shadowwalker/unstated#3]
![image](https://user-images.githubusercontent.com/17657014/55295619-9b527780-53e5-11e9-9d0e-eb6f7ff743d3.png)

Apparently, Subscribe definition in weird. Then, types cannot be inferred,

**Comment by shadowwalker** [comment]
@danilofuchs This works fine for me, I was validating in the test file here: https://github.com/shadowwalker/unstated/blob/59e48cdb0b952bd52911a1d2b528b46ef031aa6f/src/index.test.tsx#L35-L43

Could you please share the full piece of the code and the environments (VS Code version, typescript version, etc)

**Comment by danilofuchs** [comment]
I used the embedded editor in CodeSandbox: https://codesandbox.io/s/4x8vlvjzy0

It did work after adding `"allowSyntheticDefaultImports": true` to my `tsconfig.json` file.

It is set by default in create-react-app, but CodeSandbox template does not.
Maybe add it to the docs to avoid further issues.
