### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by rators** [shadowwalker/unstated#5]
Want to switch over to this library. Although, seeing how the last issue did not get a reply from the author I'm a little hesitant to make the switch.

**Comment by shadowwalker** [comment]
Hi, @rators this library would still be working if you are trying to find a simple alternative for original unstated. Sorry for the late reply, if you are block on something, I'm happy to help you out. Please pin me directly through email: weiwio@outlook.com if I don't reply the message here.
